import { ShieldCheck, Zap, Lock } from "lucide-react";

export function Hero() {
  return (
    <section className="text-center space-y-4 py-4 sm:py-6">
      {/* Badge */}
      <div className="inline-flex items-center gap-2 rounded-full border border-border bg-muted/60 px-3.5 py-1 text-xs font-medium text-muted-foreground shadow-xs">
        <span className="flex size-2 rounded-full bg-emerald-500 animate-pulse" />
        <span>Phase 2 Live — Text & Image AI Detection</span>
      </div>

      {/* Main Headline */}
      <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl lg:text-5xl text-foreground">
        Analyze Content for AI Markers in Seconds
      </h1>

      {/* Subtitle */}
      <p className="mx-auto max-w-2xl text-sm leading-relaxed text-muted-foreground sm:text-base">
        Detect whether text, essays, and synthetic images were generated by AI models. Fast, private analysis powered by open models with automatic failover.
      </p>

      {/* Feature Highlights */}
      <div className="flex flex-wrap items-center justify-center gap-4 sm:gap-8 pt-2 text-xs font-medium text-muted-foreground">
        <div className="flex items-center gap-1.5">
          <Zap className="size-3.5 text-amber-500" />
          <span>Fast inference response</span>
        </div>
        <div className="flex items-center gap-1.5">
          <Lock className="size-3.5 text-emerald-500" />
          <span>100% private — No data stored</span>
        </div>
        <div className="flex items-center gap-1.5">
          <ShieldCheck className="size-3.5 text-blue-500" />
          <span>10 free scans daily</span>
        </div>
      </div>
    </section>
  );
}
